USE [WEBTECLAT]
GO

/****** Object:  Table [dbo].[TBCategory]    Script Date: 23/09/2021 23:45:09 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TBCategory](
	[idCategory] [int] IDENTITY(1,1) NOT NULL,
	[nameCategory] [nchar](60) NOT NULL,
 CONSTRAINT [PK_TBCategory] PRIMARY KEY CLUSTERED 
(
	[idCategory] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

