//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBTEST.Infra.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WEBTECLATEntities : DbContext
    {
        public WEBTECLATEntities()
            : base("name=WEBTECLATEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBCategory> TBCategories { get; set; }
        public virtual DbSet<TBProduct> TBProducts { get; set; }
    
        public virtual ObjectResult<SP_CONSULT_PRODUCT_DATA_Result> SP_CONSULT_PRODUCT_DATA(string pRODUCT_NAME)
        {
            var pRODUCT_NAMEParameter = pRODUCT_NAME != null ?
                new ObjectParameter("PRODUCT_NAME", pRODUCT_NAME) :
                new ObjectParameter("PRODUCT_NAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CONSULT_PRODUCT_DATA_Result>("SP_CONSULT_PRODUCT_DATA", pRODUCT_NAMEParameter);
        }
    }
}
