//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBTEST.Infra.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBProduct
    {
        public int idProduct { get; set; }
        public string nameProduct { get; set; }
        public decimal priceProduct { get; set; }
        public byte[] imageProduct { get; set; }
        public string descriptopnProduct { get; set; }
        public int amountProduct { get; set; }
        public DateTime createdDateProduct { get; set; } = DateTime.Now;
        public int idCategoryProduct { get; set; }
    
        public virtual TBCategory TBCategory { get; set; }
    }
}
